title: "Dheeraj Maske"
description: "Minimalist blog with blogs, projects, and more."
author: "Dheeraj Maske"
email: "dheerajmaske2001@gmail.com"

# GA4 Measurement ID (https://analytics.google.com → Admin → Data streams)
google_analytics: "G-KZ3YWGZWWP"

baseurl: ""
url: "https://dheeraj-work.netlify.app"

paginate: 5 # Number of posts per page
paginate_path: "/page:num" # Pagination URL structure

# Social Links
social_links:
  twitter: "https://twitter.com/Dheeraj_maske" # Replace with your Twitter handle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap




# Navigation Links
navigation:
  - name: Blogs
    link: /
  - name: Projects
    link: /projects/
  - name: Talks
    link: /talks/
  - name: About
    link: /about/
